# Generated by Django 4.2.1 on 2023-05-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_state_alter_item_item_brand_alter_item_item_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resale_name', models.CharField(max_length=30)),
                ('resale_itens', models.ManyToManyField(to='inventory.item')),
            ],
        ),
    ]
